---
- name: modify repository
  apt_repository:
    repo: 'deb http://dl.bintray.com/rundeck/rundeck-deb /'
    state: present
  when: ansible_os_family == 'Debian'

- name: install in Debian family
  apt:
    name: "rundeck={{ rundeck_version }}*"
    state: present
    force: yes
  when: ansible_os_family == 'Debian'

- name: install in EL family
  package:
    name: "rundeck-{{ rundeck_version }}*"
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install rundeck-cli
  package:
    name: 'rundeck-cli'
    state: present
  when: rundeck_cli
