---
- block:
    - include: dependencies.yml
    - include: mysql.yml
    - include: nginx.yml
    - include: install.yml
    - include: setup.yml
    - include: config.yml
  rescue:
    - meta: flush_handlers
