---
- block:
    - include: dependencies.yml
    - include: mysql.yml
    - include: "{{ item }}.yml"
      with_items: "{{ rundeck_webserver }}"
    - include: install.yml
    - include: setup.yml
    - include: config.yml
  rescue:
    - meta: flush_handlers
