---
- name: modify nginx config
  template:
    src: nginx/rundeck.conf.j2
    dest: /etc/nginx/sites-enabled/rundeck.conf
    owner: root
    group: root
    mode: 0644
  notify: "restart {{ rundeck_webserver }}"
  when: rundeck_webserver is defined
